### ISSUE TITLE
jcenter ends :(

### ISSUE THREAD

**Issue by bugs84** [keb-kebish/keb#10]
jcenter will end - we have to publish artifact elsewhere (prabably mavenCentral()  )

**Comment by bugs84** [comment]
Request for domain owner ship:
https://issues.sonatype.org/browse/OSSRH-66329

**Comment by BierDav** [comment]
Are there any news about switching to mavenCentral()?

**Comment by bugs84** [comment]
Yes,
we have already approved repository on mavenCentral.
Now we need just adjust publish plugin and Upload artifacts to MavenCentral.

**Comment by bugs84** [comment]
It is uploaded - Hopefully they will synchronize it into MavenCentral

**Comment by bugs84** [comment]
Successfully uploaded version 1.1  to Maven Central

https://search.maven.org/artifact/org.kebish/keb-core/1.1/jar
https://search.maven.org/artifact/org.kebish/keb-junit5/1.1/jar
https://search.maven.org/artifact/org.kebish/keb-bobril/1.1/jar
